name: Build + tests

on:
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v2
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: install and configure allurectl
        uses: allure-framework/setup-allurectl@v1
        with:
          arguments: build